### ISSUE TITLE
奖杯页面的汇总的UI改进

### ISSUE THREAD

**Issue by swsoyee** [swsoyee/psnine-enhanced-version#3]
现在的存在以下情况：

1. [x] 奖杯图标上边缘和标题（已获得 / 未获得）距离太近。
2. [x] 配色无法兼顾正常和黑夜模式。
3. [x] 追加金银铜各类奖杯的汇总在标题上，如这样的形式
   ```
   ⬇已获得奖杯：10 （ 0 / 1 / 3 /6 ）
   ```
4. [x] 可按标题进行折叠（默认展开或者默认折叠在配置选项中可以更改）
5. [ ] 现在的Hover弹出的样式是垂直的，或许调整为水平的比较好，顺便把`获得时间`和`珍惜度`也纳入进来。

**Comment by mordom0404** [comment]
要不加下权限还有微信或qq吧....

**Comment by swsoyee** [comment]
加QQ吧电脑操作起来比较方便：274537807
