### ISSUE TITLE
P9设置面板UI美化

### ISSUE THREAD

**Issue by swsoyee** [swsoyee/psnine-enhanced-version#4]
1. [ ] 二选一的下拉菜单是否换成switch形式的比较好，节省一次鼠标点击（现在需要2次点击才能完成选择）；
2. [x] `以英文逗号隔开`等这种提示可以结合tippy.js使用节省空间；
3. [ ] 是否可以增加`Tab`页面或者较为明显的区块来配置设置选项（便于设置分类）；
4. [ ] 高亮ID或者屏蔽ID用`换行符`是否比`逗号分隔符`要好；
5. [x] 汇率因为都是同一类的设置，可能弄成水平排列比较好（设置面板的大小再弄大些就能装下了）；
6. [ ] 新增的hover显示编辑 + 楼层信息可以追加switch开关设置；
7. [ ] 高亮色彩的配置追加（包括管理员ID配色，和楼主标志的配色也追加成可设置的）；

因为这个设置面板的新增和localstorage这个还不怎么了解，所以就交给dalao了。

**Comment by mordom0404** [comment]
两个推荐的原则：适度开放、轻量化
1.考虑过模拟一个switch，最后用的原生的select-option，原因之一是switch组件无法避免使用js，第二是在桌面端switch对应的是checkbox（推荐用这个）
2.如果有兴趣的话可以使用纯html+css实现tippy效果，这样可以在一定程度上减小插件体积。
3.颜色配置后来想了想不建议，需求不大，并且本来css能解决的事情变成了js要做的。

**Comment by swsoyee** [comment]
说得挺有道理的，悉心接受
1. 既然是只有True和False，的确一个带有label的checkbox就可以解决了，还可以减少设置页面的空间。
2. tippy的这个原生实现倒是可以的，不过最近没有太多业余时间来研究这个，所以还是打算默认先用着。
3. 那这个暂时就不管了吧
4. 毕竟汇率变动也不会差太多，现有的也只是一个大概换算，所以删掉我也觉得是完全没有问题的。只不过可以变动的设置都提供给用户，调不调就看用户的意思了。如果影响效率的话的确去除掉是比较好的。
