### ISSUE TITLE
希望增加 热门 标签功能的开关

### ISSUE THREAD

**Issue by sugarkingdom** [swsoyee/psnine-enhanced-version#46]
夜晚模式下，红色的按钮和文字有点扎眼，希望能加个开关控制一下。
当然不加也无所谓，手动把 addHotTag 相关的方法注释掉就行了。

**Comment by swsoyee** [comment]
好的，待会稍微调整一下颜色和加个设置条

**Comment by swsoyee** [comment]
已在 ec1a1645732df21ef9f053b2030b29f75569ec1a 和 c0f7d105e1816010df0293bd92a7ab49673f01e8 完成该功能。
