### ISSUE TITLE
设置面板中除了开关型、textarea型的设置意外的设置无法成功设置

### ISSUE THREAD

**Issue by swsoyee** [swsoyee/psnine-enhanced-version#51]
## 调查
```
git reset --hard b3ee91d9939f147a28936b0ecdf6265eb4d6ff34
```
回退到 b3ee91d 可以设置成功，bug定位于 #49 对于设置面板进行的调整 @Nathaniel-Wu

**Comment by Nathaniel-Wu** [comment]
因为我之前加入了对local storage中选项的类型检查，当选项类型有变化的时候会用默认值，为的是应对从binary变成enum的情况。之前存储选项的时候number会被存成string，所以检查的时候通不过，被改回默认值。https://github.com/swsoyee/psnine-enhanced-version/pull/52 中已修复，`Number()`一下就可以了
