### ISSUE TITLE
内置夜间模式的切换时的屏闪问题

### ISSUE THREAD

**Issue by swsoyee** [swsoyee/psnine-enhanced-version#54]
@Nathaniel-Wu 我看了下纯CSS自动生成的脚本js，似乎按照下面这种方式实现的夜间模式可以消除屏闪问题。
https://greasyfork.org/zh-CN/scripts/376181-p9%E5%A4%9C%E9%97%B4%E6%A8%A1%E5%BC%8F/code

**Comment by Nathaniel-Wu** [comment]
好像关键是这个：
```
// no head yet, stick it whereever
document.documentElement.appendChild(node);
```
我试试看
