### ISSUE TITLE
macOS下Safari中插件无法正常工作

### ISSUE THREAD

**Issue by paradises** [swsoyee/psnine-enhanced-version#57]
系统条件：macOS 10.15.6
插件工作环境：Safari tampermonkey（macOS App Store中购入）

在所述条件下能够成功加载插件，但是插件功能无法实现

**Comment by swsoyee** [comment]
感谢报告，能否打开Safari的控制台查看一下是否有错误信息并提供一下截图？
[操作方法](https://guide.teambition.net/hc/kb/article/1169601/)

此外所使用的脚本是否是最新版本0.9.31？

第三个登录P9后在 `我的` 的下拉菜单中是否有 `插件设置` 一选项？

**Comment by paradises** [comment]
> 感谢报告，能否打开Safari的控制台查看一下是否有错误信息并提供一下截图？
> [操作方法](https://guide.teambition.net/hc/kb/article/1169601/)
> 
> 此外所使用的脚本是否是最新版本0.9.31？
> 
> 第三个登录P9后在 `我的` 的下拉菜单中是否有 `插件设置` 一选项？

感谢响应，使用脚本版本为最新0.9.31版本，插件开启后未有“插件设置选项”，但有趣的是P9的夜间模式能够正确启动
控制台中有错误信息，截图附后
<img width="1440" alt="截屏2020-08-24 20 49 40" src="https://user-images.githubusercontent.com/10516345/91046797-a4339100-e64b-11ea-9487-341c66e0800a.png">
再一次感谢！

**Comment by swsoyee** [comment]
@paradises 感谢！
@Nathaniel-Wu 这部分有什么头绪吗？

**Comment by Nathaniel-Wu** [comment]
> @paradises 感谢！
> 
> @Nathaniel-Wu 这部分有什么头绪吗？

我等会看一下，最近没有在用Safari

**Comment by Nathaniel-Wu** [comment]
Tampermonkey Safari版要收费，我用的这个开源的[userscripts](https://github.com/quoid/userscripts)测试的，一些meta key不支持所以测试不全面，如果还有问题请再回复

**Comment by swsoyee** [comment]
@Nathaniel-Wu 感谢！
@paradises 已经更新了，可以更新到 `0.9.32` 版本测试一下了

**Comment by paradises** [comment]
@swsoyee 更新至0.9.32后功能已可正常使用 感谢各位大佬！
@Nathaniel-Wu 我愿意赞助大佬一个Safari的Tampermonkey以方便后续开发😂
